// <auto-generated />
using System;
using DataLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLibrary.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220421135707_MatchesAdded")]
    partial class MatchesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataLibrary.Models.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Defeats")
                        .HasColumnType("int");

                    b.Property<string>("FavFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 1,
                            Defeats = 0,
                            FavFood = "Pizza",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-9.jpg",
                            Loves = "Wheels",
                            Name = "Rasmus",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Defeats = 0,
                            FavFood = "Fika",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-8.jpg",
                            Loves = "Meetings",
                            Name = "Jimmy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            Defeats = 0,
                            FavFood = "Pancakes",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-7.jpg",
                            Loves = "Intellisense",
                            Name = "Claes",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 2,
                            Defeats = 0,
                            FavFood = "Korv",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-1.jpg",
                            Loves = "Korvar",
                            Name = "Korven",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 2,
                            Defeats = 0,
                            FavFood = "Sallad",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-2.jpg",
                            Loves = "Jumping",
                            Name = "Patrik",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 4,
                            Defeats = 0,
                            FavFood = "Bark",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-3.jpg",
                            Loves = "Kvivksilver",
                            Name = "Pontus",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Age = 7,
                            Defeats = 0,
                            FavFood = "Popcorn",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-4.jpg",
                            Loves = "Berras Bio",
                            Name = "Mikael",
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 10,
                            Defeats = 0,
                            FavFood = "Bark",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-5.jpg",
                            Loves = "Träd",
                            Name = "Bävern",
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            Age = 6,
                            Defeats = 0,
                            FavFood = "Blötmat",
                            Games = 0,
                            ImgName = "/images/hamsters/hamster-6.jpg",
                            Loves = "Lekar",
                            Name = "Kattis",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("DataLibrary.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Hamster1Id")
                        .HasColumnType("int");

                    b.Property<int>("Hamster1Win")
                        .HasColumnType("int");

                    b.Property<int>("Hamster2Id")
                        .HasColumnType("int");

                    b.Property<int>("Hamster2Win")
                        .HasColumnType("int");

                    b.Property<int?>("HamsterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HamsterId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DataLibrary.Models.Match", b =>
                {
                    b.HasOne("DataLibrary.Models.Hamster", "Hamster")
                        .WithMany()
                        .HasForeignKey("HamsterId");

                    b.Navigation("Hamster");
                });
#pragma warning restore 612, 618
        }
    }
}
